[window]
padding = { x = 4, y = 4 }
decorations = "full"
opacity = 0.95

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Monaco", style = "Regular" }
size = 14

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
]
